compounds/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from .api import *  # NOQA
from .views import *  # NOQA


router = DefaultRouter()
router.register(r"identity/en", EnglishIdentityViewSet)
router.register(r"identity/ch", ChineseIdentityViewSet)
router.register(r'compounds', CompoundViewSet)
# router.register(r'structures', StructureViewSet)
router.register(r'herbs', HerbViewSet)
router.register(r'cids', CIDViewSet)
router.register(r'cass', CASViewSet)
router.register(r'chembls', ChEMBLViewSet)
router.register(r'prescriptions', PrescriptionViewSet)
router.register(r'keggcompounds', KEGGCompoundViewSet)
router.register(r'keggpathways', KEGGPathwayViewSet)
router.register(r'keggpathwaycategories', KEGGPathwayCategoryViewSet)
router.register(r'keggsimilarities', KEGGSimilarityViewSet)
router.register(r'taxonomies', TCMTaxonomyViewSet)
apiurls = router.urls

compounds_urls = [
    url(r"^(?P<pk>\d+)/detail/$", CompoundDetailView.as_view(), name="compound_detail"),
    url(
        r"^(?P<pk>\d+)/related-compounds$",
        CompoundRelatedCompoundsListView.as_view(),
        name="compound_related_compounds"
    ),
    url(
        r'^(?P<pk>\d+)/related-herbs$',
        CompoundRelatedHerbsListView.as_view(),
        name="compound_related_herbs"
    ),
]

herb_urls = [
    url(r'^(?P<pk>\d+)/detail/$', HerbDetailView.as_view(), name="herb_detail"),
    url(
        r'^(?P<pk>\d+)/related-compounds$',
        HerbRelatedCompoundsView.as_view(),
        name='herb_related_compounds'
        ),
    url(
        r'^(?P<pk>\d+)/related-prescription$',
        HerbRelatedPrescriptionView.as_view(),
        name='herb_related_prescription'
        ),

]


prescription_urls = [
    url(r'^(?P<pk>\d+)/detail/$', PrescriptionDetailView.as_view(), name='prescription_detail'),
]

search_url = [
    url(r'^$', SearchView.as_view(), name='search'),

    url(r'^structure/$', StructureSearchView.as_view(), name='structure-search'),
    url(r'^identify/$', IdentifySearchView.as_view(), name='identify-search'),
]

browse_urls = [
    url(r"^$", BrowseView.as_view(), name='browse'),
    url(r"^browse-herbs", HerbsBrowseListView.as_view(), name='browse-herbs'),
    url(r"^browse-prescriptions", PrescriptionBrowseListView.as_view(), name='browse-prescriptions'),
    url(r"^browse-pathways", PathwaysBrowseListView.as_view(), name="browse-pathways")
]

pathway_urls = [
    url(r'^(?P<pk>\d+)/detail/$', PathwayDetailView.as_view(), name='pathway_detail'),
]
# url config
urlpatterns = [
    url(r"^api/", include(apiurls)),

    url(r'^search/', include(search_url)),
    # compounds
    url(r"compounds/", include(compounds_urls)),

    # herbs
    url(r"^herbs/", include(herb_urls)),

    # prescription
    url(r'^prescription/', include(prescription_urls)),
    url(r'^browse/', include(browse_urls)),

    # kegg pathway
    url(
        r'^tcm-pathway/(?P<cpd_id>\d+)/(?P<kegg_pathway_id>\w+)/',
        compound_pathway_mapping_view,
        name='compound_pathway_mapping_view'
    ),
    url(r'^pathway/', include(pathway_urls)),
]

yatcm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView
from rest_framework_swagger.views import get_swagger_view
from .views import IndexView, AboutView, ContactView

schema_view = get_swagger_view(title="YaTCM API")

urlpatterns = [
    url(r"^$", IndexView.as_view(), name="index"),
    url(r'^yatcm/about/$', AboutView.as_view(), name="about"),
    url(r'^yatcm/contact/$', ContactView.as_view(), name="contact"),
    url(r'^yatcm/admin/', admin.site.urls),
    url('^yatcm/graphql', csrf_exempt(GraphQLView.as_view(graphiql=True)), name="graphql"),
    url(r"^yatcm/", include('compounds.urls')),
    # url(r'^docs/', include('rest_framework_docs.urls')),
    url(r'yatcm/api-auth', include("rest_framework.urls", namespace='rest_framework')),
    url(r"^yatcm/docs/$", schema_view),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

compounds/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.core.urlresolvers import reverse
from django.core.files import File

from mptt.models import TreeForeignKey, MPTTModel
from django_rdkit.models.fields import *
from django_rdkit.models import *
from django_rdkit.config import config
from rdkit import Chem
from rdkit.Chem import Descriptors
from rdkit.Chem.Crippen import MolLogP
from rdkit.Chem.Lipinski import NumHAcceptors, NumHDonors, NumRotatableBonds

import urllib2
from django.core.files.storage import get_storage_class
import itertools as it
import xml.etree.cElementTree as et

# Create your models here.

__all__ = [
    "Compound", "ChEMBL", "CAS", "CID",
    "TCMTaxonomy", "KEGGSimilarity", "KEGGPathwayCategory",
    "KEGGCompound", "KEGGPathway", 'Herb', 'Prescription',
    'EnglishIdentity', 'ChineseIdentity', 'CHEMBLTarget',
    'CHEMBLCompound'
]


class CHEMBLTarget(models.Model):
    chembl_id = models.CharField(max_length=64)
    name = models.CharField(max_length=1024, blank=True, null=True)
    
    def get_chembl_url(self):
        return 'https://www.ebi.ac.uk/chembl/target/inspect/{}'.format(self.chembl_id)


class CHEMBLCompound(models.Model):
    chembl_id = models.CharField(max_length=64)
    name = models.CharField(max_length=1024, blank=True, null=True)


class Identity(models.Model):
    identity = models.CharField(max_length=1024)
    compound = models.ForeignKey(
        "Compound", on_delete=models.CASCADE, null=True, blank=True,
        # related_name="%(class)s_related_compound"
    )

    class Meta:
        abstract = True


@python_2_unicode_compatible
class EnglishIdentity(Identity):
    def __str__(self):
        return self.identity


@python_2_unicode_compatible
class ChineseIdentity(Identity):
    pinyin = models.CharField(max_length=1024, blank=True)

    def __str__(self):
        return self.identity

    # @python_2_unicode_compatible
    # class Compound(models.Model):
    """
    store basic information of compound.
    """
    # english_name = models.CharField(max_length=1024, blank=True)
    # chinese_name = models.CharField(max_length=1024, blank=True)
    # phonetic_name = models.CharField(max_length=1024, blank=True)
    # synonyms = models.CharField(max_length=1024, blank=True)
    # describe = models.TextField(blank=True)

    # @property
    # def english_name(self):
    #     return self.englishidentity_set.all()[0] or ""
    #
    # @property
    # def chinese_name(self):
    #     return self.chineseidentity_set.all()[0] or ""
    #
    # def __str__(self):
    #     return '{}'.format(self.english_name.indentity)


@python_2_unicode_compatible
class Compound(models.Model):
    """
    store the structure information.
    """
    english_name = models.CharField(max_length=1024, blank=True)
    chinese_name = models.CharField(max_length=1024, blank=True)
    # synonyms = models.CharField(max_length=1024, blank=True)

    smiles = models.CharField(max_length=1024, blank=True)
    mol = MolField(null=True, blank=True)
    mol_block = models.TextField(blank=True)
    bfp = BfpField(blank=True, null=True)
    mol_file = models.FileField(upload_to='mol_files/', blank=True, null=True)
    mol_image = models.ImageField(upload_to='mol_images/', blank=True, null=True)

    related_compounds = models.ManyToManyField(
        'self', blank=True
    )
    related_ChEMBL_compounds = models.ManyToManyField(CHEMBLCompound, blank=True)
    related_ChEMBL_targets = models.ManyToManyField(CHEMBLTarget, blank=True)
    first_created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    # compound's calculated values
    formula = models.CharField(max_length=1024, blank=True)
    mol_weight = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    alogp = models.DecimalField(
        max_digits=9,
        decimal_places=2,
        verbose_name=_('Calculated ALogP'),
        blank=True,
        null=True
    )
    hba = models.SmallIntegerField(
        verbose_name=_('Number hydrogen bond acceptors'),
        blank=True,
        null=True,
    )
    hbd = models.SmallIntegerField(
        verbose_name=_('Number hydrogen bond donors'),
        blank=True,
        null=True
    )
    psa = models.DecimalField(
        max_digits=9,
        decimal_places=2,
        verbose_name=_('Polar surface area'),
        blank=True,
        null=True
    )
    rtb = models.SmallIntegerField(
        verbose_name=_('Number rotatable bonds'),
        blank=True,
        null=True
    )

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None, *args, **kwargs):
        smiles = self.smiles
        if smiles:
            try:
                self.mol = Chem.MolFromSmiles(smiles)
                self.mol_block = Chem.MolToMolBlock(self.mol)
                self.mol_weight = Descriptors.ExactMolWt(self.mol)
                self.alogp = MolLogP(self.mol)
                self.hba = NumHAcceptors(self.mol)
                self.hbd = NumHDonors(self.mol)
                self.psa = Chem.MolSurf.TPSA(self.mol)
                self.rtb = NumRotatableBonds(self.mol)

                super(Compound, self).save(*args, **kwargs)
                self.formula = Chem.rdMolDescriptors.CalcMolFormula(self.mol)
                self.bfp = MORGANBV_FP(Value(smiles))
            except (ValueError, TypeError):
                print "Error when storing mol object"
                pass
        super(Compound, self).save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.english_name or self.chinese_name or self.pk)

    def get_absolute_url(self):
        return reverse("compound_detail", args=[self.pk])

    def get_kegg_pathways(self):
        li = list(set(it.chain.from_iterable([x.pathway.all() for x in self.keggcompound_set.all()])))
        return li

    class Meta:
        ordering = ['pk']


@python_2_unicode_compatible
class Herb(models.Model):
    name = models.CharField(max_length=1024, blank=True)
    chinese_name = models.CharField(max_length=1024, blank=True)
    phonetic_name = models.CharField(max_length=1024, blank=True)
    describe = models.TextField(blank=True)
    medicinal_part = models.CharField(max_length=1024, blank=True)
    image = models.ImageField(upload_to='herb_images/', blank=True, null=True)
    image_url = models.URLField(blank=True, max_length=2048)
    compounds = models.ManyToManyField('Compound', blank=True)
    wiki_link = models.URLField(blank=True)
    wiki_chinese = models.URLField(blank=True)
    taxonomy = models.ForeignKey('TCMTaxonomy', blank=True, on_delete=models.CASCADE, null=True)

    related_herbs = models.ManyToManyField("self", blank=True)

    def get_absolute_url(self):
        return reverse("herb_detail", args=[self.pk])

    def __str__(self):
        return self.name or self.chinese_name

        # def save(self, force_insert=False, force_update=False, using=None,
        #          update_fields=None):
        #     if self.image_url:
        #         wiki_image = urllib2.urlopen(self.image_url)
        #         img = File(wiki_image)
        #         ima_name = '{}.jpg'.format(self.pk)
        #         self.img.save(ima_name, img)
        #     super(Herb, self).save()

    class Meta:
        ordering = ['id']


@python_2_unicode_compatible
class Prescription(models.Model):
    english_name = models.CharField(max_length=1024, blank=True)
    chinese_name = models.CharField(max_length=1024, blank=True)
    phonetic_name = models.CharField(max_length=1024, blank=True)
    zucheng = models.TextField(blank=True)
    yongfa = models.TextField(blank=True)
    fangjie = models.TextField(blank=True)
    tradition_usage = models.TextField(blank=True)
    modern_usage = models.TextField(blank=True)
    modern_usage_en = models.TextField(blank=True)

    main_prescription = models.ForeignKey("self", blank=True, null=True, on_delete=CASCADE)
    herbs = models.ManyToManyField(Herb, blank=True)

    def get_absolute_url(self):
        return reverse("prescription_detail", args=[self.pk])

    def __str__(self):
        return '{}'.format(self.english_name or self.chinese_name or self.pk)


@python_2_unicode_compatible
class CAS(models.Model):
    cas = models.CharField(
        _("CAS Registry Number"),
        max_length=1024,
        blank=True, null=True
    )
    url = models.URLField(
        _('URL link to chemfinder database.'),
        blank=True,
        max_length=1024
    )

    compound = models.ForeignKey(Compound, related_name="cas", on_delete=CASCADE, blank=True, null=True)

    class Meta:
        verbose_name_plural = _('CAS')

    def __str__(self):
        return self.cas


@python_2_unicode_compatible
class ChEMBL(models.Model):
    chembl_id = models.CharField(
        _("ChEMBL ID"),
        max_length=1024,
        blank=True,
        null=True,
    )
    url = models.URLField(
        _("URL link to ChEMBL database."),
        blank=True,
        max_length=1024
    )
    compound = models.ForeignKey(Compound, related_name='chembl', on_delete=CASCADE, blank=True, null=True)

    class Meta:
        verbose_name_plural = _("ChEMBL ID")

    def __str__(self):
        return str(self.chembl_id)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.url = "https://www.ebi.ac.uk/chembl/compound/inspect/{}".format(self.chembl_id)
        super(ChEMBL, self).save()


@python_2_unicode_compatible
class CID(models.Model):
    cid = models.BigIntegerField(
        _("PubChem Compound Identification"),
        blank=True,
        null=True,
    )
    url = models.URLField(
        _("URL link to PubChem."),
        blank=True,
        max_length=1024
    )

compounds/templates/compound_detail.html
{% extends "base.html" %}
{% load static staticfiles i18n %}
{% block content %}
    {% if compound %}
        <!-- compound basic information -->
        <div id="compound-basic-info" class="panel panel-default">

            <div class="panel-heading h4"><strong>{{ compound.english_name }}'s basic information</strong></div>
            <div class="panel-body">
                {#                <p><em>{{ compound.describe }}</em></p>#}
                <table class="table text-left">
                    <tbody>
                    <tr>
                        <th>Yatcm ID:</th>
                        <td>{{ compound.pk }}</td>
                    </tr>
                    <tr>
                        <th>English Name</th>
                        <td>
                            {{ compound.english_name }}&nbsp;

                        </td>
                    </tr>
                    <tr>
                        <th>Chinese Name</th>
                        <td> {{ compound.chinese_name }}&nbsp;</td>
                    </tr>
                    <tr>
                        <th>Synonyms</th>
                        <td>
                            {% for synonym in compound.englishidentity_set.all %}
                                [{{ synonym.identity }}]
                            {% endfor %}
                        </td>
                    </tr>
                    {#                    <tr>#}
                    {#                        <th>Useful Links</th>#}
                    {#                        <td>#}
                    {#                            {% for cid in compound.cid.all %}#}
                    {#                                <a href={{ cid.url }}>[{{ cid.cid }}]&nbsp;</a>#}
                    {#                            {% endfor %}#}
                    {#                            {% for cas in compound.cas.all %}#}
                    {#                                <a href={{ cas.url }}>[{{ cas.cas }}]&nbsp;</a>#}
                    {#                            {% endfor %}#}
                    {#                            {% for chembl in compound.chembl.all %}#}
                    {#                                <a href={{ chembl.url }}>[{{ chembl.chembl_id }}]&nbsp;</a>#}
                    {#                            {% endfor %}#}
                    {#                        </td>#}
                    {#                    </tr>#}
                    </tbody>
                </table>
            </div>

        </div>

        <!-- compound structure information -->
        <div id="compound-structure" class="container">
            <h4><strong>Structure information</strong></h4>
            <div class="row">
                <div class="col-md-4">
                    <img class="img-responsive" src="{{ compound.mol_image.url }}" alt="compound picture"
                         style="height: 300px;">
                </div>
                <div class="col-md-8">
                    <table class="table">
                        <tr>
                            <th>Smiles</th>
                        </tr>
                        <tr>
                            <td>{{ compound.smiles }}</td>
                        </tr>
                        <tr>
                            <th>Formula</th>
                        </tr>
                        <tr>
                            <td>{{ compound.formula }}</td>
                        </tr>
                        <tr>
                            <th>Mol weight</th>
                        </tr>
                        <tr>
                            <td>{{ compound.mol_weight }}</td>
                        </tr>
                        <tr>
                            <th>Calculate attributes</th>
                        </tr>
                        <tr>
                            <td>
                                Alogp:{{ compound.alogp }};
                                PSA:{{ compound.psa }};
                                HBA:{{ compound.hba }};
                                HBD:{{ compound.hbd }};
                                RTB:{{ compound.rtb }}
                            </td>
                        </tr>
                        <tr>
                            <th>Mol2 file</th>
                        </tr>
                        <tr>
                            <td><a href="{{ compound.mol_file.url }}">{{ compound.english_name }}</a></td>
                        </tr>
                    </table>
                </div>
            </div>

        </div>

        <!-- compound related herbs-->
        <div id="related_herbs">
            <h4>Related Herbs</h4>
            <table class="table table-responsive">
                <tr>
                    <th style="width: 33%">Related Herbs</th>
                    {# todo: change the href to compound related herbs list view #}
                    <td><a href="{% url "compound_related_herbs" compound.pk %}">{{ compound.herb_set.count }}
                        records</a></td>
                </tr>
            </table>
        </div>

        <!-- compound related compounds -->
        <div id="related_compounds">
            <h4>Similar compounds in ChEMBL</h4>
            <table class="table table-responsive">
                <tr>
                    <th style="width: 33%">Related Compounds</th>
                    <td>
                        <a href="{% url "compound_related_compounds" compound.pk %}">
                            {{ compound.related_compounds.count }} records
                        </a>
                    </td>
                </tr>
            </table>
        </div>
	<!-- target prediction using SEA -->
	{% if compound.related_ChEMBL_targets.all %}
	<div>
	  <h4 class='page-header'>Potential protein targets ({{compound.related_ChEMBL_targets.all | length}})(predicted by SEA<sup>1</sup>.)</h4>
<div class='row container well-sm'>
	{% for target in compound.related_ChEMBL_targets.all %}
              <i>({{forloop.counter}}).</i>
	      <a href='{{target.get_chembl_url}}'>{{target.chembl_id}}</a>
	{% endfor %}
</div>
	    </div>
        <i>1. Wang et al. 2016 DOI: 10.1186/s13321-016-0130-x</i>
	{% endif %}
        <!-- compound related pathways -->
        <div>
            {% if compound.get_kegg_pathways %}
                <h4>KEGG metabolism pathway mappings</h4>
                {% for pathway in compound.get_kegg_pathways %}
                    {% include 'includes/kegg_pathway_list.html' %}
                {% endfor %}
            {% endif %}
        </div>
    {% endif %}
{% endblock %}

compounds/templates/compound_list.html
{% extends "base.html" %}
{% load static staticfiles i18n %}

{% block css %}
{% endblock css %}

{% block content %}
    <div class="container">
        <div class="row">
            <div id="compound_list">
                {% for compound in compounds %}
                    <div class="col-xs-6 col-md-3">
                        <a href="{{ compound.get_absolute_url }}" class="thumbnail">
                            <img src="{{ compound.mol_image.url }}" alt="compound image" style="width: 300px">
                            <abbr title="{{ compound.english_name }}">{{ compound.english_name | truncatechars:19}}</abbr>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{#    {% if is_paginated %}#}
{#        <div class="pagination">#}
{#            <span class="page-links">#}
{#                {% if page_obj.has_previous %}#}
{#                    <a class="btn btn-default" href="/yatcm/structure/all?page={{ page_obj.previous_page_number }}">previous</a>#}
{#                {% endif %}#}
{#                <span class="page-current">#}
{#                    Page {{ structures.number }} of {{ page_obj.paginator.num_pages }}#}
{#                </span>#}
{#                {% if page_obj.has_next %}#}
{#                    <a class="btn btn-default"#}
{#                       href="/yatcm/structure/all?page={{ page_obj.next_page_number }}">next</a>#}
{#                {% endif %}#}
{#            </span>#}
{#        </div>#}
{#    {% endif %}#}
{% endblock content %}
{% block js %}
{% endblock js %}

compounds/templates/herb_detail.html
{% extends "base.html" %}
{% load staticfiles static i18n %}
{% block css %}

{% endblock css %}

{% block content %}

    <!-- herb information -->
    <div class="container">
        <div class="row">
            <h4>{{ herb.name }}</h4>
            <div id="herb_image" class="col-md-4">
                <a href="{{ herb.wiki_link }}">
                    <img class="img-responsive" src="{{ herb.image_url }}" alt="{{ herb.chinese_name }} image">
                </a>
            </div>
            <div id="herb_info" class="col-md-8">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ herb.name }}</div>
                    <div class="panel-body"><p>{{ herb.describe }}</p></div>

                    <!-- list group -->
                    <ul class="list-group">
                        <li class="list-group-item">
                            Chinese name: {{ herb.chinese_name }}
                        </li>
                        <li class="list-group-item">
                            phonetic name: {{ herb.phonetic_name }}
                        </li>
                        <li class="list-group-item">
                            medicinal part: {{ herb.medicinal_part }}
                        </li>
                        <li class="list-group-item">
                            link:
                            <a href="{{ herb.wiki_link }}">wiki</a>&nbsp;
                            <a href="{{ herb.wiki_chinese }}">维基</a>
                        </li>
                        {% if taxonomy_list %}
                            <li class="list-group-item">
                            taxonomy:
                                {% for taxononmy in taxonomy_list %}
                                    <a href="{{ taxonomy.ncbi_link }}">-->{{ taxononmy.name }}</a>
                                {% endfor %}
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- herb ingredient -->
    <div id="ingredient">
    <hr>
    <h4>Ingredients</h4>
    <table class="table table-responsive">
        <tr>
            <th style="width: 33%">Ingredients</th>
            <td><a href="{% url "herb_related_compounds" herb.pk %}">{{ herb.compounds.count}} records</a></td>
        </tr>
    </table>
    </div>

    <div id="herb_related_prescription">
        <h4>Prescriptions</h4>
        <table class="table table-responsive">
            <tr>
                <th style="width: 33%">Prescriptions</th>
                <td><a href="{% url 'herb_related_prescription' herb.pk %}">{{ herb.prescription_set.count}} records</a></td>
            </tr>
        </table>
    </div>

{% endblock content%}

{% block js %}

{% endblock js %}

compounds/templates/herbs_browse_list_view.html
{% extends 'browse.html' %}
{% load static staticfiles bootstrap_pagination %}
{% block css %}
    <link href="{% static 'css/browse.css' %}" rel="stylesheet">
{% endblock %}
{% block browse-table %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Image</th>
            <th>Name</th>
            <th>Phonetic name</th>
            <th>Chinese name</th>
            <th>Ingredients</th>
            <th>Detail</th>
        </tr>
        </thead>
        <tbody>
        {% for herb in  herb_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><img src="{{ herb.image_url }}" class="img-table img-thumbnail img-table"></td>
                <td>{{ herb.name }}</td>
                <td>{{ herb.phonetic_name }}</td>
                <td> {{ herb.chinese_name }}</td>
                <td><a href="{% url "herb_related_compounds" herb.pk %}">{{ herb.compounds.all | length }}</a></td>
            <td><a href="{% url 'herb_detail' herb.id %}">view</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% bootstrap_paginate page_obj range=10 %}
{% endblock %}

compounds/templates/prescription_detail.html
{% extends 'base.html' %}
{% load staticfiles static i18n %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8" id="prescription_info">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title"><h3 class="text-center"><strong>{{ prescription.chinese_name }}</strong></h3></div>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">
                            <strong>中文名：</strong>{{ prescription.chinese_name }}
                        </li>
                        <li class="list-group-item">
                            <strong>英文名： </strong>{{ prescription.english_name }}
                        </li>
                        <li class="list-group-item">
                            <strong>配方组成：</strong>{{ prescription.zucheng }}
                        </li>
                        <li class="list-group-item">
                            <strong>方解:</strong>{{ prescription.fangjie }}
                        </li>
                        <li class="list-group-item">
                            <strong>使用方法：</strong>{{ prescription.yongfa }}
                        </li>

                        <li class="list-group-item">
                            <strong>传统用法：</strong>{{ prescription.tradition_usage }}
                        </li>
                        <li class="list-group-item">
                            <strong>现代用法： </strong>{{ prescription.modern_usage }}
                        </li>
                        <li class="list-group-item">
                            <strong>Modern Usage:</strong>{{ prescription.modern_usage_en }}
                        </li>
                    </ul>

                </div>
            </div>
            <div class="col-md-4">
                <div class="col-md-12" id="related_prescription">
                    <ul class="list-group">

                        {% if prescription.main_prescription %}
                            <li class="list-group-item list-group-item-success"><h4>主方</h4></li>
                            <li class="list-group-item">
                                <a href="{% url 'prescription_detail' prescription.main_prescription_id %}">
                                    {{prescription.main_prescription.chinese_name }}
                                </a>
                            </li>
                        {% else %}
                            <li class="list-group-item list-group-item-success"><h4>副方</h4></li>
                            {% for pre in prescription.prescription_set.all %}
                                <li class="list-group-item">
                                    <a href="{{ pre.get_absolute_url }}">
                                        {{ pre.chinese_name }}
                                    </a>
                                </li>
                            {% endfor %}
                        {% endif %}
                    </ul>
                </div>  <!-- related prescription -->

                <div id="related_herb" class="col-md-12">
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-success"><h4>中药成分</h4></li>
                        {% for herb in prescription.herbs.all %}
                            <li class="list-group-item">
                                <a href="{{ herb.get_absolute_url }}">{{ herb.chinese_name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

compounds/templates/prescriptions_browse_list_view.html
{% extends 'browse.html' %}
{% load static staticfiles bootstrap_pagination %}
{% block css %}
    <link href="{% static 'css/browse.css' %}" rel="stylesheet">
{% endblock %}
{% block browse-table %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Phonetic name</th>
            <th>Chinese name</th>
            <th>Components</th>
            <td>Detail</td>

        </tr>
        </thead>
        <tbody>
        {% for prescription in  prescription_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ prescription.name }}</td>
                <td>{{ prescription.phonetic_name }}</td>
                <td> {{ prescription.chinese_name }}</td>
                {% if prescription.herbs.all %}
                    <td>{{ prescription.herbs.all | length }}</td>
                    {% else %}
                    <td></td>
                {% endif %}
            <td><a href="{% url 'prescription_detail' prescription.id %}">view</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% bootstrap_paginate page_obj range=10 %}
{% endblock %}